<link rel="stylesheet" href="../assets/css/texteditor/css/froala_editor.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/froala_style.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/code_view.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/draggable.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/colors.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/emoticons.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/image_manager.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/image.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/line_breaker.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/table.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/char_counter.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/video.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/fullscreen.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/file.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/quick_insert.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/help.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/third_party/spell_checker.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/third_party/embedly.min.css?v=<?php echo time(); ?>">
<link rel="stylesheet" href="../assets/css/texteditor/css/plugins/special_characters.css?v=<?php echo time(); ?>">